### ISSUE TITLE
Go Black?

### ISSUE THREAD

**Issue by eyeseast** [eyeseast/python-frontmatter#54]
Python has always appealed to my inner copy editor. [Black](https://black.readthedocs.io/en/stable/index.html) might save me from myself. I like it's [style](https://black.readthedocs.io/en/stable/the_black_code_style.html).

**Comment by eyeseast** [comment]
This is probably the way to go: https://black.readthedocs.io/en/stable/version_control_integration.html

```yaml
repos:
-   repo: https://github.com/python/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7
```
